//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.Scrum.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Teams.Apps.Scrum.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        internal static string AstreixSymbol {
            get {
                return ResourceManager.GetString("AstreixSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any blockers?.
        /// </summary>
        internal static string BlockersText {
            get {
                return ResourceManager.GetString("BlockersText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not running a scrum right now. Use this command to end an active scrum..
        /// </summary>
        internal static string CompleteScrumErrorText {
            get {
                return ResourceManager.GetString("CompleteScrumErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end scrum.
        /// </summary>
        internal static string CompleteScrumText {
            get {
                return ResourceManager.GetString("CompleteScrumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End scrum.
        /// </summary>
        internal static string CompleteScrumTitle {
            get {
                return ResourceManager.GetString("CompleteScrumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One scrum runs at a time. When you’re done, select End scrum at the bottom of the form. Once you end a scrum, no one can make any more updates to that scrum. Just start a new scrum when you’re ready to get status updates again..
        /// </summary>
        internal static string CompleteScrumTourText {
            get {
                return ResourceManager.GetString("CompleteScrumTourText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong and I can’t do that right now. Try again in a few minutes. .
        /// </summary>
        internal static string GenericErrorMessage {
            get {
                return ResourceManager.GetString("GenericErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only be used in group chat with no more than 20 members..
        /// </summary>
        internal static string MemberCountErrorMessage {
            get {
                return ResourceManager.GetString("MemberCountErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Active Scrum.
        /// </summary>
        internal static string NoActiveScrumTitle {
            get {
                return ResourceManager.GetString("NoActiveScrumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} You are not a part of the running scrum. Only active members of the scrum can mark it as completed..
        /// </summary>
        internal static string NoPartOfCompleteScrumText {
            get {
                return ResourceManager.GetString("NoPartOfCompleteScrumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} You&apos;re not in the scrum that&apos;s currently running. Once that scrum has ended, you can start a new one..
        /// </summary>
        internal static string NoPartOfScrumStartText {
            get {
                return ResourceManager.GetString("NoPartOfScrumStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  You are not a part of the running scrum. You’ll be able to enter your updates next scrum onwards..
        /// </summary>
        internal static string NoPartOfScrumUpdateText {
            get {
                return ResourceManager.GetString("NoPartOfScrumUpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} You are not a part of the running scrum. You’ll be able to initiate a new scrum once the active scrum is completed..
        /// </summary>
        internal static string NotPartofScrumText {
            get {
                return ResourceManager.GetString("NotPartofScrumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter info (1000 characters max).
        /// </summary>
        internal static string PlaceholderText {
            get {
                return ResourceManager.GetString("PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only run one scrum at a time. End the current scrum first, then start a new one..
        /// </summary>
        internal static string RunningScrumMessage {
            get {
                return ResourceManager.GetString("RunningScrumMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am currently designed to work only in Group chats. Please install me in a group chat to start tracking your scrum updates..
        /// </summary>
        internal static string ScopeErrorMessage {
            get {
                return ResourceManager.GetString("ScopeErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum completed by {0}, {1}.
        /// </summary>
        internal static string ScrumCompletedByText {
            get {
                return ResourceManager.GetString("ScrumCompletedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice Work! This scrum is complete..
        /// </summary>
        internal static string ScrumCompleteText {
            get {
                return ResourceManager.GetString("ScrumCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can only support below commands..
        /// </summary>
        internal static string ScrumHelpMessage {
            get {
                return ResourceManager.GetString("ScrumHelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Scrum started by {0}, {1}.
        /// </summary>
        internal static string ScrumRequestedByText {
            get {
                return ResourceManager.GetString("ScrumRequestedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update scrum.
        /// </summary>
        internal static string ScrumTaskModuleTitle {
            get {
                return ResourceManager.GetString("ScrumTaskModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrum updated by {0}, {1}.
        /// </summary>
        internal static string ScrumUpdatedByText {
            get {
                return ResourceManager.GetString("ScrumUpdatedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status details.
        /// </summary>
        internal static string ShowScrumDetailsTitle {
            get {
                return ResourceManager.GetString("ShowScrumDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scrum.
        /// </summary>
        internal static string StartCarouselCardTitle {
            get {
                return ResourceManager.GetString("StartCarouselCardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///When you ask me to start a scrum, I’ll create a form where people can enter their current status. Everyone can look at these updates.
        ///   .
        /// </summary>
        internal static string StartCommandTourTextPart1 {
            get {
                return ResourceManager.GetString("StartCommandTourTextPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to start a scrum now?.
        /// </summary>
        internal static string StartCommandTourTextPart2 {
            get {
                return ResourceManager.GetString("StartCommandTourTextPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start scrum.
        /// </summary>
        internal static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string SubmitTitle {
            get {
                return ResourceManager.GetString("SubmitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a tour.
        /// </summary>
        internal static string TakeATourButtonText {
            get {
                return ResourceManager.GetString("TakeATourButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here’s a tour of what I can do..
        /// </summary>
        internal static string TakeTourWelcomeMessage {
            get {
                return ResourceManager.GetString("TakeTourWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What will you do today? *(required)*.
        /// </summary>
        internal static string TodayText {
            get {
                return ResourceManager.GetString("TodayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can&apos;t be empty..
        /// </summary>
        internal static string TodayValidationText {
            get {
                return ResourceManager.GetString("TodayValidationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated on {0}.
        /// </summary>
        internal static string UpdateScrumTimeStampText {
            get {
                return ResourceManager.GetString("UpdateScrumTimeStampText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update status.
        /// </summary>
        internal static string UpdateScrumTitle {
            get {
                return ResourceManager.GetString("UpdateScrumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not from the expected tenant.
        /// </summary>
        internal static string WarningTextForTenantFailure {
            get {
                return ResourceManager.GetString("WarningTextForTenantFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///I help you get status updates from your team. Everyone in the group chat can participate..
        /// </summary>
        internal static string WelcomeCardContentPart1 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Want to know more? Take a tour!.
        /// </summary>
        internal static string WelcomeCardContentPart2 {
            get {
                return ResourceManager.GetString("WelcomeCardContentPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What did you do yesterday?*(required)*.
        /// </summary>
        internal static string YesterdayText {
            get {
                return ResourceManager.GetString("YesterdayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field can&apos;t be empty..
        /// </summary>
        internal static string YesterdayValidationText {
            get {
                return ResourceManager.GetString("YesterdayValidationText", resourceCulture);
            }
        }
    }
}
